version: "3.9"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=${PUBLIC_NAME}/prometheus
      - --web.route-prefix=/
      - --web.config.file=/etc/prometheus/web.yml
        #- --web.listen-address=127.0.0.1:9090
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./web.yml:/etc/prometheus/web.yml
      - prom-storage:/prometheus
    networks:
      - monitoring
    links:
      - node-exporter
      - grafana
      - blackbox-exporter

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    hostname: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - monitoring
  
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=${PUBLIC_NAME}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PW}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./datasource-prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - monitoring
  
  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    hostname: blackbox-exporter
    restart: unless-stopped
    command:
      - --config.file=/etc/blackbox_exporter/config.yml
      - --web.external-url=${PUBLIC_NAME}/bbox
      - --web.route-prefix=/
    volumes:
      - ./blackbox-config.yml:/etc/blackbox_exporter/config.yml:ro
    ports:
      - 127.0.0.1:9115:9115
    networks:
      - monitoring
    

volumes:
  prom-storage:

networks:
  monitoring:
    driver: bridge
